apiVersion: v1
kind: Namespace
metadata:
  name: diffhe-physics-lab
  labels:
    name: diffhe-physics-lab
    app.kubernetes.io/name: diffhe-physics-lab
    app.kubernetes.io/version: "1.0.0-dev"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: diffhe-config
  namespace: diffhe-physics-lab
data:
  DIFFHE_ENV: "production"
  DIFFHE_LOG_LEVEL: "INFO"
  DIFFHE_BACKEND: "numpy"
  DIFFHE_MAX_WORKERS: "4"
  DIFFHE_CACHE_SIZE: "1000"

---
apiVersion: v1
kind: Secret
metadata:
  name: diffhe-secrets
  namespace: diffhe-physics-lab
type: Opaque
data:
  POSTGRES_PASSWORD: ZGlmZmhlMTIz  # base64 encoded "diffhe123"
  REDIS_PASSWORD: ZGlmZmhlMTIz
  JWT_SECRET: c3VwZXJfc2VjcmV0X2tleQ==  # base64 encoded "super_secret_key"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffhe-app
  namespace: diffhe-physics-lab
  labels:
    app: diffhe-app
    version: v1.0.0-dev
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: diffhe-app
  template:
    metadata:
      labels:
        app: diffhe-app
        version: v1.0.0-dev
    spec:
      containers:
      - name: diffhe-app
        image: diffhe-physics-lab:1.0.0-dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: DIFFHE_ENV
          valueFrom:
            configMapKeyRef:
              name: diffhe-config
              key: DIFFHE_ENV
        - name: DIFFHE_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: diffhe-config
              key: DIFFHE_LOG_LEVEL
        - name: DIFFHE_BACKEND
          valueFrom:
            configMapKeyRef:
              name: diffhe-config
              key: DIFFHE_BACKEND
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: diffhe-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: diffhe-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: diffhe-data-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: diffhe-logs-pvc
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: diffhe-app-service
  namespace: diffhe-physics-lab
  labels:
    app: diffhe-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: diffhe-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diffhe-app-ingress
  namespace: diffhe-physics-lab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - diffhe-physics-lab.com
    secretName: diffhe-tls
  rules:
  - host: diffhe-physics-lab.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diffhe-app-service
            port:
              number: 8000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diffhe-data-pvc
  namespace: diffhe-physics-lab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diffhe-logs-pvc
  namespace: diffhe-physics-lab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: diffhe-app-hpa
  namespace: diffhe-physics-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: diffhe-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60

---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: diffhe-app-metrics
  namespace: diffhe-physics-lab
spec:
  selector:
    matchLabels:
      app: diffhe-app
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: diffhe-network-policy
  namespace: diffhe-physics-lab
spec:
  podSelector:
    matchLabels:
      app: diffhe-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nginx-ingress
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
  - to: []
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 443   # HTTPS
    - protocol: TCP
      port: 80    # HTTP
    - protocol: UDP
      port: 53    # DNS